---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  client_rb:
    chef_license: accept

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[ppa_kernel::default]
    attributes:
